### ISSUE TITLE
Migrate Wroc# competition app to .NET Core

### ISSUE THREAD

**Issue by patrikulus** [WTobor/DevAdventCalendar#1]
We want to use this app as base for our competition app, but it must be migrated to .NET Core if we want to run it inside docker.

**Comment by patrikulus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Przepisanie aplikacji od Radka na .NET Core](https://trello.com/c/XpUfSTcJ/37-przepisanie-aplikacji-od-radka-na-net-core)

**Comment by WTobor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Przepisanie aplikacji Wroc# na .NET Core](https://trello.com/c/1aPxbz0O/1-przepisanie-aplikacji-wroc-na-net-core)
