### ISSUE TITLE
Different style for opened window

### ISSUE THREAD

**Issue by blaze4ever** [WTobor/DevAdventCalendar#114]
Add class "opened" to opened day and create custom style for it.

**Comment by WTobor** [comment]
@blaze4ever - do you have any idea how it should look like?

**Comment by blaze4ever** [comment]
@WTobor yeah opened padlock on opened window and closed when user didn't open window. 
Can someone add div before "panel-body" ? <div class="opened"></div> when opened and <div class="missed"></div> when task has passed and user didn't open it. Thanks :) I was trying to do it but I am to weak in ASP :)

**Comment by WTobor** [comment]
@smiechuskce - what do you think about it? Can you do it?

**Comment by WTobor** [comment]
closed due to finish first project iteration
