### ISSUE TITLE
Fix registration in Safari browser

### ISSUE THREAD

**Issue by WTobor** [WTobor/DevAdventCalendar#122]
"Na początku nie mogłem się zarejestrować – link do potwierdzenia nie działał, pojawiał się błąd. Zarejestrowałem się więc przez github, ale nie mogę się zalogować… Po wybraniu github nic się nie dzieje, a po wpisaniu danych logowania także błąd o nieudanym logowaniu."

**Comment by blaze4ever** [comment]
Dziwne u mnie działa ;) 

Maybe something with email provider? Do we know which email provider user used to register?

![image](https://user-images.githubusercontent.com/25966458/49605027-be1cd400-f98f-11e8-9a5a-d8aeb9d8abbb.png)
![image](https://user-images.githubusercontent.com/25966458/49605038-c7a63c00-f98f-11e8-8b07-cd6d7e9453c2.png)

**Comment by WTobor** [comment]
cannot reproduce
