### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by WTobor** [WTobor/DevAdventCalendar#32]
Add some logic to handle errors. For now (e.x. when db throw error) whole error is shown.
![image](https://user-images.githubusercontent.com/22730914/47614541-ab1a0880-daa1-11e8-92f6-54b80e959976.png)

Default error page can look like:
![image](https://user-images.githubusercontent.com/22730914/47614585-95f1a980-daa2-11e8-8a1e-dc227e3ff55a.png)

Sad Santa:
![sad_santa](https://user-images.githubusercontent.com/22730914/47614593-a30e9880-daa2-11e8-991e-72b206c5a79b.JPG)

**Comment by olekstomek** [comment]
Error page doesn't work. 
Go to e.g. https://devadventcalendar.pl/test404, you get

> Nie można znaleźć tej strony na devadventcalendar.plNie znaleziono strony internetowej pod adresem https://devadventcalendar.pl/test404
> HTTP ERROR 404

![image](https://user-images.githubusercontent.com/26818304/69988066-28376d00-1541-11ea-940e-6426557215cc.png)
