### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by patrikulus** [WTobor/DevAdventCalendar#4]
We can use circleci, codeship, travis or anything else what is as-a-service and integrates with GitHub.

**Comment by KrystianKolad** [comment]
Travis is free for open source projects. I can setup this but I need some details like where do I deploy it :D

**Comment by WTobor** [comment]
@patrikulus - could you help?

**Comment by patrikulus** [comment]
It's done already ;) I've created PR #69 with production ready compose. @KrystianKolad you could also review it if you want :)
