### ISSUE TITLE
Add external login providers

### ISSUE THREAD

**Issue by WTobor** [WTobor/DevAdventCalendar#60]
Add fb/tt/google/Github providers

**Comment by KrystianKolad** [comment]
If you create all the apps you want and give me keys i can do it :)

**Comment by WTobor** [comment]
@patrikulus could you help with that?

**Comment by patrikulus** [comment]
@KrystianKolad Let me handle the apps and I will get back to you when I'm ready ;)

**Comment by WTobor** [comment]
@patrikulus any update?

**Comment by patrikulus** [comment]
Work in progress ;)

**Comment by patrikulus** [comment]
I've also updated app.env on production server to include all secrets.
